FROM python:3.10

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["sh", "-c", "python manage.py migrate && python manage.py collectstatic --noinput && cp -r /app/collected_static/. /backend_static/static/ && gunicorn --bind 0.0.0.0:9000 kittygram_backend.wsgi"]
